blank_issues_enabled: true
contact_links:
  - name: Scash Security Policy
    url: https://github.com/scash-project/scash/blob/scash_master/SECURITY-SCASH.md
    about: View security policy
  - name: Scash Developers
    url: https://s.cash
    about: Scash Project homepage
